### ISSUE TITLE
Consider adjustment to TXT RData format

### ISSUE THREAD

**Issue by mistermoe** [decentralized-identity/did-dht#79]
![image](https://github.com/TBD54566975/did-dht-method/assets/4887440/b3a5bec2-1318-4ca6-bdda-87685c9459e8)

context: I'm in the middle of implementing `did:dht` in dart. 

Is there any rationale behind `_did.TLD` storing all the relationships? parsing a TXT record that into a DID Document could be `O(n)` if each `_kN_did.`  had a rel (relationships) property e.g. `rel=auth,asm` vs. having to look up the relationships in the root entry.

**Comment by thereisnogabe** [comment]
your point is correct. the design was chosen because I saw the biggest risk to the TXT size limit of being a key + a key ID. this is why there's guidance on suggested KIDs.

having longer TXT records is possible, but awkward, and I did not want to risk dealing with variations in tooling (still may have to). so - anything to reduce the size of a single record is 👍 

that and I believe it's worth it to separate out relationships from key definitions, as is done in DID core itself (see [verification methods](https://www.w3.org/TR/did-core/#verification-methods) opposed to [verification relationships](https://www.w3.org/TR/did-core/#verification-relationships).

marking this as pending close
