### ISSUE TITLE
Include rationale behind using DNS Packet as wire protocol

### ISSUE THREAD

**Issue by mistermoe** [decentralized-identity/did-dht#80]
is the primary reason behind using DNS packets as the wire protocol because `did:dht` leverages pkarr relays? 

I did notice the gateway `/did/:did` endpoint which is nice, but i wanted sig verification. found it a bit strange that i was making HTTP requests to get back a DNS packet. 

I had to [handroll](https://github.com/TBD54566975/tbdex-dart/tree/did-dht-resolver/lib/src/dns_packet) DNS packet decoding because there wasn't a third party lib available to do so. 

Not complaining since the work is done, and I imagine most languages to have dns packet decoding libs. Just more-so wondering if there's specific reasons for having selected it. If compression is the sole reason, is there a comparison available between DNS packet sizes for this usecase vs. say CBOR?

I would think KRPC protocol mentioned in [bep005](https://www.bittorrent.org/beps/bep_0005.html) would even make more sense because thats the protocol used to communicate with Mainline DHT nodes over UDP. This way relays wouldn't have to transform DNS records into KRPC payloads. 

Anyway, wondering if it'd be helpful to include rationale behind using DNS packets or simply defer to rationale behind using pkarr.

**Comment by thereisnogabe** [comment]
yes this is because of our reliance on Pkarr. there is some [rationale here](https://github.com/Nuhvi/pkarr), but paging @nuhvi for additional explanation. my understanding is that the semantics of DNS match nicely, along with the ambitions to eventually have Pkarr servers be DNS servers and vice versa.

The spec does say we build upon [Pkarr in the abstract](https://did-dht.com/#abstract) but I'm happy to add more text to make this clearer. Is there a specific section where you think it would make sense to address this?

also

> I did notice the gateway /did/:did endpoint which is nice, but i wanted sig verification

The idea is to trust these gateways as little as possible.

**Comment by Nuhvi** [comment]
> I would think KRPC protocol mentioned in [bep005](https://www.bittorrent.org/beps/bep_0005.html) would even make more sense because thats the protocol used to communicate with Mainline DHT nodes over UDP. This way relays wouldn't have to transform DNS records into KRPC payloads

This is almost but not entirely true. You still use KRPC in Mainline, but the payload of [BEP_0044](https://www.bittorrent.org/beps/bep_0044.html) is not KRPC (that wouldn't make sense) but rather just any valid (arbitrary, hence the name of the BEP) Bencode. It happens though that binary string is just as valid Bencode as any.

The relay actually help you avoid using or implementing Bencode at all because it just concatenates signature, 6 bytes timestamp and the raw value, but that is beside the point.

The point here is what would be the best format to store Routing data in the arbitrary part of BEP_0044?

You can for sure use CBOR or even JSON (as I started with), but there is no upside for that. As you said any language that supports JSON would also support deserializing DNS packets, the encoding is actually very smart and economic, I couldn't have done much better, but I would have lost on one very important upside:

1. If you ever get to the point of serving Pkarr records over regular DNS servers like 1.1.1.1 they sure would appreciate that the raw data they receive (and cache) needs no transformation whatsoever at request time. Same applies to local DNS servers on one's machine.

2. Encoding IPv4 and IPv6 is first class, you can't do it any better than that.

Maybe that is too theoretical of an advantage, but all other encoding choices don't have anything over DNS packets either, so *the* routing packet encoding for a routing protocol, couldn't get any more conservative than that.

Of course, you can decide to stop using Pkarr and just use BEP_0044 directly and send the DID as a Bencode or JSON object, but then you make it very hard to leverage DNS servers and many caching layers.

If you convince 1.1.1.1 to respond to queries like `o4dksfbqk85ogzdb5osziw6befigbuxmuxkuxq8434q89uj56uyy` by using Mainline as the [Root name server](https://en.wikipedia.org/wiki/Root_name_server) then every recursive DNS resolver downstream will be helping cache responses for everyone reducing the load over Mainline, without actually implementing any special code themselves, because you already chose to speak their language.

**Comment by Nuhvi** [comment]
For inspiration https://iroh.computer/blog/iroh-global-node-discovery

**Comment by thereisnogabe** [comment]
Closing, if you feel the current spec should be adjusted @mistermoe please re-open.
