### ISSUE TITLE
Consider returning signature from `GET /dids/:did`

### ISSUE THREAD

**Issue by mistermoe** [decentralized-identity/did-dht#98]
Currently, in order to independently verify that a DID Document was indeed produced and published by the controller of a `did:dht`, implementers have to resolve using pkarr relays as noted here:

![image](https://github.com/TBD54566975/did-dht-method/assets/4887440/98464b5a-825d-4154-ab98-5abce1677cf2)

Are there any technical reasons preventing us from being able to return the signature from `GET /dids/:did`? It would be nice to leverage the simplicity of resolving a `did:dht` using the gateway endpoint while also being able to independently verify that the resolved document hasn't been tampered with. 

This would also be beneficial for [historical resolution](https://did-dht.com/#historical-resolution).

Personally feel like providing a means to perform an integrity check is important as it prevents folks from falling victim to a bad actor gateway

**Comment by thereisnogabe** [comment]
my main concern is mixing layers (signed BEP44 messages and DID Documents), since DID Documents can have an optional proof property. this could be confusing since the underlying data that you'd be verifying _is not_ a DID Document. without doing a transformation yourself you're trusting the server. it is safest to use the relay API directly for this reason.

what do you think?

**Comment by mistermoe** [comment]
it seems like we're already mixing layers as per how `PUT /dids/:did` works yeah as per [6.3.2](https://did-dht.com/#register-or-update-a-did)

![image](https://github.com/TBD54566975/did-dht-method/assets/4887440/6231cbe8-3a24-40cc-873e-8d7fd3980cd5)

**Comment by thereisnogabe** [comment]
you're right, though this is my biggest sticking point

> without doing a transformation yourself you're trusting the server

I would be more OK with removing the API you call out and keeping the GET did API as a utility.

**Comment by frankhinek** [comment]
I wonder if there are approaches we can take that make it easier to adopt and use using a familiar REST API?

One option is simply to provide high-quality, complete implementations in every major language.  

... but I am still left wondering if there's a benefit to interacting with the DHT Gateways in the context of create, update, and deactivate operations if Register/Update APIs aren't available?  Does it mean that all of those have to go through a Pkarr relay? (in practice, it seems that DHT Gateways would also be Pkarr relays?)

Is there any value to using the DID Resolution Options `accept` property to specify and return alternate representations of the DID document that might include data that isn't typically included?

**Comment by thereisnogabe** [comment]
> I wonder if there are approaches we can take that make it easier to adopt and use using a familiar REST API?

that was the intention with the current API; though I'm concerned about adding a signature which could lead users into a false sense of trust since the DID data returned by the server pertaining to the data in the signature necessitates trusting the node, this is a problem. 

Yes, it's true you need to trust the server for resolving a DID too, and publishing. However I think there is a larger risk of providing a false sense of security for a malicious node that return an altered DID Document state with a previously valid signature.

**Until we can find a way to avoid this I'm not comfortable with this change proposal.** I'm not sure adding a note warning to the contrary is good enough since it puts the burden on clients to decode the payload and compare it, and in that case what's the benefit of adding to this API?

> but I am still left wondering if there's a benefit to interacting with the DHT Gateways in the context of create, update, and deactivate operations if Register/Update APIs aren't available?

the main benefit is the additional functionality you get around type indexing, retention proofs, and in the future, other types of indexing around aliases (maybe more too).

> Does it mean that all of those have to go through a Pkarr relay? (in practice, it seems that DHT Gateways would also be Pkarr relays?)

DHT Gateways are Pkarr relays, so the answer is yes. This is true today will remain true.

> Is there any value to using the DID Resolution Options accept property to specify and return alternate representations of the DID document that might include data that isn't typically included?

This is an interesting idea that we can/should explore...but may end up being more complex than sticking to something the spec itself defines.

**Comment by frankhinek** [comment]
> that was the intention with the current API; though I'm concerned about adding a signature which could lead users into a false sense of trust since the DID data returned by the server pertaining to the data in the signature necessitates trusting the node, this is a problem.
>
> Yes, it's true you need to trust the server for resolving a DID too, and publishing. However I think there is a larger risk of providing a false sense of security for a malicious node that return an altered DID Document state with a previously valid signature.

I could be wrong but I believe the motivation behind asking for the signature be returned in the `GET /did:id` response is precisely to allow for an additional level of verification so that the DHT gateway need not be trusted.  In other words, the caller could take the DID Document, sequence number, and signature ... convert the DID document to a DNS packet, encode, bencode, and then verify the signature.

It seems that the trust involved in resolving a DID to a DID document isn't any worse than calling `GET /did/:id` given that either way you don't know whether the DHT Gateway tampered with the results.  In many cases its sufficient to trust the gateway but there may be cases where additional measures are needed in high assurance scenarios.

Perhaps there should be a separate interface (or optional query parameter) that can be called to retrieve the signature information that would be needed to verify the returned DID document?  That way someone has to go out of their way to request this and may be more likely to understand the tradeoffs.

On a related topic, what about signature availability for [Historical Resolution](https://did-dht.com/#historical-resolution)?  Since mainline DHT nodes don't keep the old state, it would seem that being able to verify signatures for what a Gateway claims is the historical state of a DID's keys would be crucial for any high assurance scenarios.

**Comment by decentralgabe** [comment]
after further consideration I am on board with your assessment, and the original suggestion

> I could be wrong but I believe the motivation behind asking for the signature be returned in the GET /did:id response is precisely to allow for an additional level of verification so that the DHT gateway need not be trusted. In other words, the caller could take the DID Document, sequence number, and signature ... convert the DID document to a DNS packet, encode, bencode, and then verify the signature.

I will add guidance saying that this is an obligation of a conformant client and add signature data to both the get and historical APIs

**Comment by thereisnogabe** [comment]
Going to implement this I realized that without also including the `seq` and `v` in original form the data cannot be verified properly.

This means that the DID API would turn into the Pkarr API and also return DID Documents.

So we have two options:
1. Keep things as-is, resulting in two fetches -- one for Pkarr info (verifiable), one for DID Docs (untrusted)
2. Amend the DID API to add in the content of the Pkarr API

My main problem, now, with (2) is that it makes returning the DID Document less meaningful. Why return it at all if it needs to be reconstructed from the Pkarr response? What utility is it really adding?

So...after even further consideration...I'm back to my original position to keep these APIs separate.

To @mistermoe 's original point

> It would be nice to leverage the simplicity of resolving a did:dht using the gateway endpoint while also being able to independently verify that the resolved document hasn't been tampered with.

This can be accomplished today with two API calls. If the main benefit is returning strings instead of bytes, or requesting with a DID instead of a Pkarr ID, we can consider additional API endpoints.

**Comment by thereisnogabe** [comment]
After chatting with @frankhinek  -- as a convenience will provide a b64URL encoded Pkarr Get response (`seq:sig:v`) alongside the DID API, also for historical data.

**Comment by thereisnogabe** [comment]
#110
